name: Publish Project

on:
  push:
    branches:
      - master
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build Backend
    uses: ./.github/workflows/build-api.yaml
    with:
      runtests: true
      sonar: false
      ephytoenvironment: uat
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      READ_SOURCE_AND_PACKAGES: ${{ secrets.READ_SOURCE_AND_PACKAGES }}

  publish:
    name: Publish
    needs: [ build ]
    uses: ./.github/workflows/publish-google-artifact-registry.yaml
    with:
      ephytoenvironment: uat
    secrets:
      READ_SOURCE_AND_PACKAGES: ${{ secrets.READ_SOURCE_AND_PACKAGES }}

  dev:
    name: Deploy to dev
    needs: publish
    uses: ./.github/workflows/deploy-cloud-run.yaml
    with:
      project-id: digiplant-dev-a431
      project-number: 870437576104
      name: "ephyto-api"
      service-account: "ephyto-api-cr-svc-sa"
      environment: dev
      ephytoenvironment: uat

  buildProd:
    name: Build Backend for prod
    needs: build
    uses: ./.github/workflows/build-api.yaml
    with:
      runtests: false
      sonar: false
      ephytoenvironment: prod
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      READ_SOURCE_AND_PACKAGES: ${{ secrets.READ_SOURCE_AND_PACKAGES }}

  publishProd:
    name: Publish prod
    needs: [ buildProd ]
    uses: ./.github/workflows/publish-google-artifact-registry.yaml
    with:
      ephytoenvironment: prod
    secrets:
      READ_SOURCE_AND_PACKAGES: ${{ secrets.READ_SOURCE_AND_PACKAGES }}

  staging:
    name: Deploy to staging
    needs: publishProd
    uses: ./.github/workflows/deploy-cloud-run.yaml
    with:
      project-id: digiplant-staging-969d
      project-number: 951629907562
      name: "ephyto-api"
      service-account: "ephyto-api-cr-svc-sa"
      environment: staging
      ephytoenvironment: prod

  prod:
    name: Deploy to prod
    needs: publishProd
    uses: ./.github/workflows/deploy-cloud-run.yaml
    with:
      project-id: digiplant-prod-d23d
      project-number: 1049150207506
      name: "ephyto-api"
      service-account: "ephyto-api-cr-svc-sa"
      environment: prod
      ephytoenvironment: prod
